FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# UT HSC Dissertation Proposal Defense

This is the API for UT HSC Doctoral Dissertation Proposal Defense Form process.

## Get Student Information [/getStudentInformation/student_key]
+ Parameters
    + student_key (string) - ID of the student whose information is to be retrieved

### Retrieve student information [GET]

+ Response 200 (application/json)

        {
            "student_name": "Doe, John, David",
            "student_email_address": "john.doe@uthsc.edu",
            "degree_program": "PhD",
            "academic_advisor": 
            {
                "name": "James Cooper",
                "key": "abc123",
                "department_name": "Oncology",
                "department_key": "abc123",
                "discipline_name": "Pediatric Oncology",
                "discipline_key": "abc123"
            },
            
            "major_department_chair":
            {
                "name": "Selina Meyer",
                "key": "abc123"
            },
            
            "minor_advisor": 
            {
                "name": "Jane Jones",
                "key": "abc123",
                "department_name": "Cardiology",
                "department_key": "abc123",
                "discipline_name": "Invasive Cardiology"
                "discipline_key": "abc123"
             },
             
            "second_minor_advisor": 
            {
                "name": "Gloria Chang",
                "key": "abc123",
                "department_name": "Pediatrics",
                "department_key": "abc123",
                "discipline_name": "General Pediatrics",
                "discipline_key": "abc123"
            },
            
            "dissertation_supervisor":
            {
                "name": "Rudy Randall",
                "key": "abc123",
                "department_name": "Oncology",
                "department_key": "abc123",
                "discipline_name": "General Pediatrics",
                "discipline_key": "abc123"
            },
            
            "assistant_dean":
            {
                "name": "Richard Hughes",
                "key": "abc123"
            }
        }
        
## Get all schools [/getSchools]
Is there an ID of school to be used in the query below?

### Retrieve all schools [GET]

+ Response 200 (application/json)

        {
            "schools":
            [
                {"name": "UT Medical School",
                 "key": "abc1234",
                 "external": "true"
                },
                {"name": "UT Health Science Center"
                 "key": "abc1234",
                 "external": "true"
                },
                {"name": "Baylor Medical School"
                 "key": "abc1234",
                 "external": "true"
                }
            ]

        }
        
## Get all departments of a school [/getDepartments/school_key]
Should the shcool name be used or an ID?

+ Parameters
    + school_key (string) - school selected by student

### Retrieve all departments of a school [GET]

+ Response 200 (application/json)

        {
            "departments":
            [
                {"name": "Oncology",
                 "key": "abc1234",
                 "school_key": "xyz789"
                },
                {"name": "Cardiology",
                 "key": "abc1234",
                 "school_key": "xyz789"
                },
                {"name": "Pediatrics",
                 "key": "abc1234",
                 "school_key": "xyz789"
                }
            ]

        }
        
## Get all faculty members of a department [/getFaculty/department_key]
Should the department name be used or an ID?

+ Parameters
    + department_key (string) - department selected by student

### Retrieve all faculty members of a department [GET]

+ Response 200 (application/json)

        {
            "faculties":
            [
                {"name": "James Cooper",
                 "key": "abc123",
                 "email_address": "james.cooper@uthsc.edu",
                 "department_key": "Oncology"
                }
                {"name": "Selina Meyer",
                 "key": "abc123",
                 "email_address": "selina.meyer@uthsc.edu",
                 "department_key": "Oncology"
                },
                {"name": "Gloria Chang",
                 "key": "abc123",
                 "email_address": "gloria.chang@uthsc.edu",
                 "department_key": "Oncology"                
                }
            ]

        }
        
## Update status of a process [/updateDissertationDefenseStatus]

### Update the status of a Dissertation Proposal Defense process [POST]


+ Request (application/json)

        {
            "process_id": "1234567",
            "process_start_date": "09/02/2016",
            "process_status": "incomplete",
            "student_key": "abc123",
            "dissertation_proposal_project_title": "How to cure cancer",
            "date_of_proposal_defense": "10/1/2016",
            "approvers": {
                "academic_advisor": 
                {
                    "key": "abc123",
                    "department_key": "Oncology",
                    "discipline_key": "abc123",
                    "approval_date": ""
                },
                "major_department_chair": 
                {
                    "key": "abc123",
                    "approval_date": ""
                },
                "minor_advisor": 
                {
                    "key": "abc123",
                    "department_key": "abc123",
                    "discipline_key": "abc123",
                    "approval_date": ""
                },
                "second_minor_advisor": 
                {
                    "key": "abc123",
                    "department_key": "abc123",
                    "discipline_key": "abc123",
                    "approval_date": ""
                },
                "dissertation_supervisor":
                {
                    "key": "abc123",
                    "department_key": "abc123",
                    "discipline_key": "abc123",
                    "approval_date": ""
                },
                "assistant_dean": 
                {
                    "key": "abc123",
                    "approval_date": ""
                },
                "optional_member": [
                    {
                        "key": "abc123",
                        "department_key": "abc123",
                        "discipline_key": "abc123",
                        "approval_date": ""
                    }
                ],
                "external_member": [
                    {
                        "key": "abc123",
                        "department_key": "abc123",
                        "discipline_key": "abc123",
                        "approval_date": ""
                    }
                ]
            }
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "messages": [
                    {
                        "code": "123",
                        "message": "something went wrong"
                    }
                ]
            }